
import com.itextpdf.kernel.font.PdfFont;
import com.itextpdf.kernel.font.PdfFontFactory;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfReader;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.Text;
import java.util.Scanner;


public class PDFcreator {
    void create() throws Exception {
        PdfFont font = PdfFontFactory.createFont("FreeSans.ttf", "CP1251", true);
        PdfReader reader = new PdfReader("Shablon.pdf");
        PdfWriter writer = new PdfWriter("Schet.pdf");
        PdfDocument pdf = new PdfDocument(reader, writer);
        Document document = new Document(pdf);
        document.setFont(font);
        Scanner read = new Scanner(System.in);
        System.out.println("Банк получателя:");
        String bankname = read.nextLine();
        Paragraph p = new Paragraph(new Text(bankname));
        p.setFixedPosition(35, 786, 100);
        p.setFontSize(10);
        document.add(p);
        System.out.println("ИНН:");
        String inn = read.nextLine();
        p = new Paragraph(new Text(inn));
        p.setFixedPosition(55, 750, 100);
        p.setFontSize(10);
        document.add(p);
        System.out.println("КПП:");
        String kpp = read.nextLine();
        p = new Paragraph(new Text(kpp));
        p.setFixedPosition(198, 750, 100);
        p.setFontSize(10);
        document.add(p);
        System.out.println("Получатель:");
        String getterperson = read.nextLine();
        p = new Paragraph(new Text(getterperson));
        p.setFixedPosition(35, 737, 100);
        p.setFontSize(10);
        document.add(p);
        p = new Paragraph(new Text("0447326525"));
        p.setFixedPosition(353, 786, 100);
        p.setFontSize(10);
        document.add(p);
        p = new Paragraph(new Text("30720445626015"));
        p.setFixedPosition(353, 775, 100);
        p.setFontSize(10);
        document.add(p);
        p = new Paragraph(new Text("40720442753711"));
        p.setFixedPosition(353, 749, 100);
        p.setFontSize(10);
        document.add(p);
        p = new Paragraph(new Text("13.01"));
        p.setFixedPosition(194, 681, 100);
        p.setFontSize(14);
        document.add(p);
        p = new Paragraph(new Text("2"));
        p.setFixedPosition((float) 250.7, (float) 681.7, 100);
        p.setFontSize(13);
        document.add(p);
        p = new Paragraph(new Text("0"));
        p.setFixedPosition((float) 256.7, (float) 681.7, 1000);
        p.setFontSize(13);
        document.add(p);
        p = new Paragraph(new Text("3"));
        p.setFixedPosition(162, 681, 1000);
        p.setFontSize(14);
        document.add(p);
        p = new Paragraph(new Text(getterperson + " ИНН " + inn + " КПП " + kpp));
        p.setFixedPosition(100, 638, 1000);
        p.setFontSize(10);
        document.add(p);
        p = new Paragraph(new Text("ИП Сидоров"));
        p.setFixedPosition(100, 605, 1000);
        p.setFontSize(10);
        document.add(p);
        p = new Paragraph(new Text("№1634738 от 13.02.2020"));
        p.setFixedPosition(100, 580, 1000);
        p.setFontSize(10);
        document.add(p);
        p = new Paragraph(new Text("Предоставление услуг по доступу \nв интернет и телефонной связи"));
        p.setFixedPosition(65, 515, 1000);
        p.setFontSize(12);
        document.add(p);
        p = new Paragraph(new Text("1"));
        p.setFixedPosition(355, 540, 1000);
        p.setFontSize(12);
        document.add(p);
        p = new Paragraph(new Text("1"));
        p.setFixedPosition(322, 540, 1000);
        p.setFontSize(12);
        document.add(p);
        p = new Paragraph(new Text(String.valueOf(MainClass.price)));
        p.setFixedPosition(390, 540, 1000);
        p.setFontSize(12);
        document.add(p);
        p = new Paragraph(new Text(String.valueOf(MainClass.price)));
        p.setFixedPosition(457, 540, 1000);
        p.setFontSize(12);
        document.add(p);
        p = new Paragraph(new Text(MainClass.price + " руб."));
        p.setFixedPosition(450, 491, 1000);
        p.setFontSize(9);
        document.add(p);
        double nds = MainClass.price/6.0;
        nds*=100;
        nds=Math.round(nds)/100.0;
        p = new Paragraph(new Text(nds + " руб."));
        p.setFixedPosition(450, 479, 1000);
        p.setFontSize(9);
        document.add(p);
        p = new Paragraph(new Text(MainClass.price + " руб."));
        p.setFixedPosition(450, 466, 1000);
        p.setFontSize(9);
        document.add(p);
        p = new Paragraph(new Text("Фёдоров Н. А."));
        p.setFixedPosition(451, 334, 1000);
        p.setFontSize(10);
        document.add(p);
        p = new Paragraph(new Text("Фёдоров Н. А."));
        p.setFixedPosition(237, 334, 1000);
        p.setFontSize(10);
        document.add(p);
        p = new Paragraph(new Text("1 на сумму " + MainClass.price + " руб."));
        p.setFixedPosition(122, 451, 1000);
        p.setFontSize(9);
        document.add(p);
        document.close();
    }
}
